[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
script = "script"
build_info = true
extra_output = ["storageLayout"]

# Solidity compiler settings
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM version
evm_version = "cancun"

# Remappings for OpenZeppelin libraries and Chainlink
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/contracts/=lib/chainlink-evm/contracts/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/"
]

# Gas limit for tests
gas_limit = 30000000

# Testing settings
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Formatting settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"

# Documentation settings
[doc]
out = "docs"
title = "NewLo Point Token"
repository = "https://github.com/your-org/newlo-point-contract"

# RPC endpoints (examples)
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
# Soneium endpoints
soneium = "${SONEIUM_RPC_URL}"
soneium-minato-testnet = "https://rpc.minato.soneium.org/"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
# Soneium Blockscout API
soneium = { key = "${SONEIUM_API_KEY}", url = "https://soneium.blockscout.com/api" }
soneium-minato-testnet = { key = "${SONEIUM_API_KEY}", url = "https://soneium-minato.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
